### ISSUE TITLE
Increase the image size and add the margin-top

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#101]
**Describe the bug**
The "About" image is small and not an "About" section margin-top 

**Expected behavior**
Increase the image size and add the margin-top to match the website

**Screenshots**
![Screenshot 2023-03-19 184316](https://user-images.githubusercontent.com/88996660/226178218-5d9247bb-ef09-40a5-8d6d-e7595942c3dc.jpg)

**Are you working on it?**
No

**Comment by kaifkhan1** [comment]
Can you please elaborate the issue?

**Comment by Tharindu37** [comment]
@kaifkhan1 Sure, go ahead

**Comment by Bingolast** [comment]
heyy is this  issue solved ?

**Comment by Tharindu37** [comment]
@Bingolast No, but it's already assigned

**Comment by Tharindu37** [comment]
@kaifkhan1 Please unassign yourself if you can't do it
