### ISSUE TITLE
Add Gap

### ISSUE THREAD

**Issue by munnokd** [Tharindu37/ProSolutions#106]
**Is your feature request related to a problem? Please describe.**
There is no space between the "Home" section and the "about" section

**Describe the solution you'd like**
Add space between the "about" section and the "Home" section.

**Screenshot**
![image](https://user-images.githubusercontent.com/81804004/226296356-5af6044c-133d-4599-b052-2bba2650df5a.png)

**Are you working on it?**
Yes

**Comment by Tharindu37** [comment]
@munnokd This issue is already added by #101.Thank you for adding the issue. You can try to add other issues.

**Comment by munnokd** [comment]
okay.
