### ISSUE TITLE
Decrease the image size.

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#107]
**Describe the bug**
The technology icons size is more. It's not better

**Expected behavior**
Decrease the image size.

**Screenshots**
![Screenshot 2023-03-20 185544](https://user-images.githubusercontent.com/88996660/226354913-2ab647ba-65ff-4965-909e-7f8012eb5c1c.jpg)

**Are you working on it?**
No

**Comment by kanhadharmikk** [comment]
i want to work on this issue

**Comment by Tharindu37** [comment]
@kanhadharmikk Sure, go ahead

**Comment by Tharindu37** [comment]
@kanhadharmikk It's a good

**Comment by Tharindu37** [comment]
@kanhadharmikk but it is not aligned.

**Comment by Tharindu37** [comment]
@kanhadharmikk Can you use the bootstrap grip system for this issue?

**Comment by kanhadharmikk** [comment]
@Tharindu37 ok , I will 
Should i make the image smaller for mobile view to?

**Comment by kanhadharmikk** [comment]
![test](https://user-images.githubusercontent.com/66997330/226386827-286500c4-a111-4d4a-891c-7a3c47cc98b9.PNG)
@Tharindu37 please review

**Comment by Tharindu37** [comment]
@kanhadharmikk It's good

**Comment by kanhadharmikk** [comment]
@Tharindu37 can you please review the PR? If there are any changes I will work on it.
