### ISSUE TITLE
Change the colour on the scroll thumb when the thumb is hovering

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#108]
**Is your feature request related to a problem? Please describe.**
Change the colour on the scroll thumb when the thumb is hovering

**Describe the solution you'd like**
Change the CSS on the file

**Are you working on it?**
No

**Comment by kanhadharmikk** [comment]
Can you please elaborate on the issue more? So that I can get the exact result of the issue.

**Comment by Tharindu37** [comment]
@kanhadharmikk Sure, You should change the colour to red in the scroll thumb
