### ISSUE TITLE
Update Readme.md file 

### ISSUE THREAD

**Issue by kanhadharmikk** [Tharindu37/ProSolutions#121]
**Describe the bug**
 There are some spelling and grammar mistakes in README.md.

**Expected behavior**
 >thechnologys 
 >desing
 >Fork the this repository

**TO**
 >Technologies
 >Design
 >Fork this Repository

**Screenshots**
![test](https://user-images.githubusercontent.com/66997330/227100713-fa72659b-e46e-4709-a9a5-3800095f3d60.PNG)

**Additional context**
Input proper spelling

**Are you working on it?**
No

**Comment by Tharindu37** [comment]
@kanhadharmikk Thank you for adding the new issue

**Comment by kanhadharmikk** [comment]
@Tharindu37 Welcome, can you please label it as a good first issue?

**Comment by Tharindu37** [comment]
@kanhadharmikk Sure

**Comment by roshan798** [comment]
I would like to work on this
