### ISSUE TITLE
Update the Readme.md file

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#127]
**Is your feature request related to a problem? Please describe.**
The ProSolution website deployed on another server. therefore we should update the Readme file with the new available link

**Describe the solution you'd like**
Add the new available link as follows.
Available at : [https://pro-solutions.vercel.app/](url)

**Are you working on it?**
No

**Comment by Yvad60** [comment]
Hi @Tharindu37,I am working on this

**Comment by Tharindu37** [comment]
@Yvad60 Sure, go ahead
