### ISSUE TITLE
BUSINESS CONSULATION SCREEN

### ISSUE THREAD

**Issue by therealtmmy** [Tharindu37/ProSolutions#128]
Business Consulation Screen is missing according to the figma design. Assign that to me and let me do the fixing.

**Comment by Tharindu37** [comment]
@therealtmmy What did you mean by business Consultation?

**Comment by therealtmmy** [comment]
![Captured](https://user-images.githubusercontent.com/107879861/227783420-6f772a94-92b3-4b94-b9c2-e29a4ab7d306.JPG)

**Comment by Tharindu37** [comment]
@therealtmmy This issue is already assigned by #23
