### ISSUE TITLE
Update the Readme.md file

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#135]
**Describe the bug**
An unwanted link is available.

**Expected behavior**
Remove the following link.
[https://pro-solutions.vercel.app/](url)

**Screenshots**
![Screenshot 2023-03-28 204653](https://user-images.githubusercontent.com/88996660/228285507-e0524654-3fb1-4510-bcce-bef5e812dac5.jpg)

**Are you working on it?**
No

**Comment by rohit-rambade** [comment]
I would like to work on this issue .

**Comment by Tharindu37** [comment]
@rohit-rambade Sure, go ahead
