### ISSUE TITLE
arrow.gif file move to the assets folder

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#136]
**Is your feature request related to a problem? Please describe.**
All images should include in one folder

**Describe the solution you'd like**
arrow.gif file move to the assets folder

**Additional context**
Resolve all outstanding issues by moving the file.

**Are you working on it?**
No

**Comment by rohit-rambade** [comment]
Hello @Tharindu37  I'll like to work on this.

**Comment by Tharindu37** [comment]
@rohit-rambade Sure, go ahead
