### ISSUE TITLE
Change the background image URL

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#14]
**Describe the bug**
Change the background image URL

**Expected behavior**
Change the URL ```C:\Users\Administrator\Desktop\P01\ProSolutions\Assests\office.jpg```
to ```assets/office.jpg```

**Are you working on it?**
No

**Comment by Navodi99** [comment]
I would like to work on this

**Comment by Tharindu37** [comment]
@Navodi99 Sure, go ahead
