### ISSUE TITLE
Add the welcome text  as following

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#20]
Add the welcome text

**Additional context**
Use the bootstrap container and row for responsive

**Are you working on it?**
No

**Comment by afzalsorathiya** [comment]
I work on this issue.

**Comment by Tharindu37** [comment]
@afzalsorathiya Sure, go ahead

**Comment by Tharindu37** [comment]
@Navodi99 Can you work on this?

**Comment by afzalsorathiya** [comment]
no

**Comment by afzalsorathiya** [comment]
Already this pull request is closed

**Comment by Tharindu37** [comment]
@afzalsorathiya yes, I will assign this issue for another contributer.

**Comment by Navodi99** [comment]
@Tharindu37 Sure

**Comment by Tharindu37** [comment]
@Navodi99 go ahead
