### ISSUE TITLE
Add about the company

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#24]
**Is your feature request related to a problem? Please describe.**
Add as follows
![Screenshot (63)](https://user-images.githubusercontent.com/88996660/213903297-21063918-e0d0-4850-b679-c08a7b7c1d2f.png)

**Additional context**
Use bootstrap 5

**Are you working on it?**
No

**Comment by BawanthaPrasad** [comment]
Could I work on this?

**Comment by Tharindu37** [comment]
@BawanthaPrasad Sure
