### ISSUE TITLE
Add the about image

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#27]
**Describe the bug**
About image is missing.

**Expected behavior**
Add the about image for the assets folder

**Additional context**
Download the about image in the resource link

**Are you working on it?**
No

**Comment by BawanthaPrasad** [comment]
Could I work on this?

**Comment by Tharindu37** [comment]
@BawanthaPrasad Sure

**Comment by Chaitu-Tatipamula** [comment]
is this done

**Comment by Tharindu37** [comment]
@Chaitu-Tatipamula yes

**Comment by Chaitu-Tatipamula** [comment]
OKAY..!
