### ISSUE TITLE
Make the about section responsive

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#28]
**Is your feature request related to a problem? Please describe.**
Make the about section responsive

**Describe the solution you'd like**
Hide the about image for mobile view.

**Are you working on it?**
No

**Comment by BawanthaPrasad** [comment]
Could I work on this?

**Comment by emergenitro** [comment]
I would like to take up this issue

**Comment by Tharindu37** [comment]
@emergenitro Sure

**Comment by Tharindu37** [comment]
@emergenitro Sorry, @BawanthaPrasad be already commented on this issue

**Comment by Tharindu37** [comment]
@BawanthaPrasad Sure
