### ISSUE TITLE
Change about image path

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#32]
**Describe the bug**
About image is not visible.

**Expected behavior**
Change about image path as follows
`src="assets/about.jpg"`

No

**Comment by Navodi99** [comment]
I would like to work on this

**Comment by emergenitro** [comment]
I would like to work on this too

**Comment by Tharindu37** [comment]
@emergenitro Sorry, @Navodi99 be already commented on this issue

**Comment by Tharindu37** [comment]
@Navodi99 Sure

**Comment by Tharindu37** [comment]
@Navodi99 You can work on this issue now
