### ISSUE TITLE
Make the welcome text section responsive

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#35]
**Describe the bug**
The welcome text is not responsive.

**Expected behavior**
The welcome text is not responsive.

**Screenshots**
![Screenshot 2023-02-26 081731](https://user-images.githubusercontent.com/88996660/221389511-88d56be2-d614-4530-8c44-7b6830db69e6.jpg)

**Are you working on it?**
No

**Comment by emergenitro** [comment]
I would like to take up this issue

**Comment by Tharindu37** [comment]
@emergenitro Sure
