### ISSUE TITLE
 Change the title of the webpage

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#42]
**Is your feature request related to a problem? Please describe.**
The website title is home. it's a not good

**Describe the solution you'd like**
Change the title to `ProSolutions`

**Are you working on it?**
No

**Comment by Yasanga-Nishaditha** [comment]
I would like to work on this.

**Comment by Tharindu37** [comment]
@Yasanga-Nishaditha Sure, goahead
