### ISSUE TITLE
Increase the size of the "about" image

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#45]
**Is your feature request related to a problem? Please describe.**
The "about" image is small. It is not good

**Describe the solution you'd like**
Increase the size of the "about" image

**Additional context**
![Screenshot 2023-03-06 091459](https://user-images.githubusercontent.com/88996660/223015688-e0047fee-fe12-4aef-8774-510c2a5a0899.jpg)
This is not good look like

**Are you working on it?**
No

**Comment by BawanthaPrasad** [comment]
I would like to work on this.

**Comment by Tharindu37** [comment]
@BawanthaPrasad Sure, goahead
