### ISSUE TITLE
 Office image does not scroll when the webpage does scroll

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#46]
**Describe the bug**
 Office image does not scroll when the webpage does scroll

**Expected behavior**
 Office image does not scroll when the webpage does scroll

**Screenshots**
![Screenshot 2023-03-06 092824](https://user-images.githubusercontent.com/88996660/223016415-75a713e7-99e7-4a14-8675-5d9ddb05293e.jpg)

**Are you working on it?**
No

**Comment by shiva0002** [comment]
Hi @Tharindu37 I would like to work on this issue.
