### ISSUE TITLE
Scroll down to the "about" section when clicking the "about" link

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#52]
**Is your feature request related to a problem? Please describe.**
should Scroll down to the "about" section when clicking the "about" link

**Describe the solution you'd like**
Use the basic HTML

**Additional context**
![Screenshot 2023-03-11 061406](https://user-images.githubusercontent.com/88996660/224454492-574e0197-e393-44a9-bf75-bbfda8289f09.jpg)

**Are you working on it?**
No

**Comment by aayushdhakal** [comment]
@Tharindu37 I would like to work on this issue.

**Comment by Tharindu37** [comment]
@aayushdhakal Sure, go ahead

**Comment by aayushdhakal** [comment]
done and can you look into it.

**Comment by Tharindu37** [comment]
![WhatsApp Image 2023-03-06 at 08 51 39](https://user-images.githubusercontent.com/88996660/224482243-47e66c5e-0217-42f8-9831-49cbfecc76b0.jpeg)

@aayushdhakal Edit the PR following this
