### ISSUE TITLE
Compress the "office" image

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#53]
**Describe the bug**
"office" image loading slowly

**Expected behavior**
Compress the image using the following link 
[https://compressjpeg.com/](url) 

**Screenshots**
![Screenshot 2023-03-11 063826](https://user-images.githubusercontent.com/88996660/224456161-7878f40f-d4ea-4e74-972e-9f7159172fd0.jpg)

**Are you working on it?**
No

**Comment by aayushdhakal** [comment]
Please can you assign me this issue.

**Comment by Tharindu37** [comment]
@aayushdhakal Sure, go ahead

**Comment by aayushdhakal** [comment]
Can you please review the changes.

**Comment by Tharindu37** [comment]
@aayushdhakal Sure, I will review
