### ISSUE TITLE
Decrease the margin-bottom of the "welcome text"

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#54]
**Describe the bug**
"Welcome text" is not good in the mobile phone view

**Screenshots**
![Screenshot 2023-03-11 104055](https://user-images.githubusercontent.com/88996660/224466364-3af2cea3-624b-4a2d-9504-fb7a48f4a1c7.jpg)

**Additional context**
the new position of "welcome text"
![Screenshot 2023-03-11 104055](https://user-images.githubusercontent.com/88996660/224466428-bb4852fe-05c3-4c46-baee-778a38b9ac69.jpg)

**Are you working on it?**
No

**Comment by AK4266** [comment]
I would like to work on this issue. Can you assign it to me

**Comment by Tharindu37** [comment]
@AK4266 Sure, go ahead

**Comment by aayushdhakal** [comment]
is this issue still available ? i would like to  work on it

**Comment by aayushdhakal** [comment]
sure.

**Comment by Tharindu37** [comment]
@aayushdhakal 
https://github.com/Tharindu37/ProSolutions/issues/53 This issue is available
