### ISSUE TITLE
Add the "Solutions" banner

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#63]
**Is your feature request related to a problem? Please describe.**
Add the "Solutions" banner

**Describe the solution you'd like**
The banner should be as follows
![Screenshot 2023-03-13 162316](https://user-images.githubusercontent.com/88996660/224682338-a499e7b6-cffc-492c-9462-54fdfc3734ce.jpg)

**Additional context**
You can download an image from the resources google drive link.

**Are you working on it?**
No

**Comment by AK4266** [comment]
i want to work on this issue can you assign it to me

**Comment by Tharindu37** [comment]
@AK4266 Sure, go ahead

**Comment by AK4266** [comment]
Hui @Tharindu37  Can you please go through this PR gh pr checkout 64 and put your thoughts? Thanks

**Comment by AK4266** [comment]
Hiii @Tharindu37 Can you please go through my PR and put your thoughts? Thanks

**Comment by Tharindu37** [comment]
@AK4266 Sure, I will review

**Comment by AK4266** [comment]
Hiii @Tharindu37 Can you please go through my PR and put your thoughts? like you asked I compressed the image. Thanks
