### ISSUE TITLE
Add the responsive navbar

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#7]
Add the responsive navbar with bootstrap 5.

**The solution**
- Create a file as 'index.html'
- Add HTML template as follows
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Home</title>
</head>
<body>

</body>
</html>
```
- After, Add the responsive navbar as follows
![Screenshot 2023-01-12 221047](https://user-images.githubusercontent.com/88996660/212127417-a5c8b535-aded-46b0-ba80-6a6f9a1118e6.jpg)

**Additional context**
You should link bootstrap 5 for the project.

**Are you working on it?**
No

**Comment by khushpreetsinghb** [comment]
I want to work on open-source projects. I can do this.

**Comment by Tharindu37** [comment]
@khushpreetsinghb Sure

**Comment by khushpreetsinghb** [comment]
#8 Added PR for the same

**Comment by Tharindu37** [comment]
@khushpreetsinghb Yes, the screenshot is required.
