### ISSUE TITLE
Remove the gap

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#71]
**Describe the bug**
There is Empty space between the "about" section and the "contributors" section

**Expected behavior**
Remove the Empty space between the "about" section and the "contributors" section.

**Screenshots**
![Screenshot 2023-03-16 134217](https://user-images.githubusercontent.com/88996660/225555802-019cfb29-b87a-48f2-af7b-d61f8aba693b.jpg)

**Are you working on it?**
No

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by Tharindu37** [comment]
@munnokd Sure, go ahead

**Comment by munnokd** [comment]
okay.

**Comment by munnokd** [comment]
I made pr upon that so you can merge it.
