### ISSUE TITLE
Add the "Technology" section

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#74]
**Is your feature request related to a problem? Please describe.**
Add the technologies that use our company.

**Describe the solution you'd like**
You should do like bellow this
![ssss](https://user-images.githubusercontent.com/88996660/225574645-70f4c43f-ec96-4a87-a337-1e67bd1def89.jpg)

**Additional context**
You can use [https://icons8.com/](url) this website for download the icon

**Are you working on it?**
No

**Comment by emergenitro** [comment]
May I take this up?

**Comment by Tharindu37** [comment]
@emergenitro Sure, go ahead
