### ISSUE TITLE
Decrese the hight of the "Solutions" banner

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#79]
**Describe the bug**
"Solutions" banner height is more

**Expected behavior**
Decrese the hight of the "Solutions" banner

**Screenshots**
![Screenshot (83)](https://user-images.githubusercontent.com/88996660/225616399-99caefa0-a800-4e21-9c1e-f5e3ac950b8a.png)

**Are you working on it?**
No

**Comment by roshan798** [comment]
I want to work on it.
Please assign me this

**Comment by Tharindu37** [comment]
@roshan798 Sure, go ahead

**Comment by Mayankjain2023** [comment]
I would like to work on this,please assign this to me.
