### ISSUE TITLE
Add the link for "Contributors" on the nav bar

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#80]
**Is your feature request related to a problem? Please describe.**
Not a link for scroll to the "Contributors" section

**Describe the solution you'd like**
Add the link for "contributors" after the "about" link

**Are you working on it?**
No

**Comment by aayushdhakal** [comment]
i would like to work on it.

**Comment by aayushdhakal** [comment]
@Tharindu37 Are you suggesting to add contributors link to the navigation bar or adding contribution link to each of the contributors in the contributors section  below about section ?

**Comment by Tharindu37** [comment]
@aayushdhakal Add to the navigation bar
