### ISSUE TITLE
Add a border around the profile Picture

### ISSUE THREAD

**Issue by BawanthaPrasad** [Tharindu37/ProSolutions#82]
**Is your feature request related to a problem? Please describe.**
Profile pictures are better with a boarder around them.

**Describe the solution you'd like**
Add a border around the below profile Picture.
![Screenshot (328)](https://user-images.githubusercontent.com/120650482/225825036-70a823d5-3d8d-46ca-a89f-030bea6505ad.png)

**Are you working on it?**
No

**Comment by aayushdhakal** [comment]
i would like to work on it.

**Comment by Tharindu37** [comment]
@aayushdhakal Sure, go ahead
