### ISSUE TITLE
Scroll down to the "Our Contributors" section

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#88]
**Is your feature request related to a problem? Please describe.**
Doesn't scroll down to the "Our Contributors" section when clicking the "Contributors" link at top of the nav bar

**Describe the solution you'd like**
Use the HTML Hyperlinks

**Are you working on it?**
No

**Comment by valanm22** [comment]
May I work on this?

**Comment by Tharindu37** [comment]
@valanm22 Sure, go ahead
