### ISSUE TITLE
Change the Scrollbar styles

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#89]
**Is your feature request related to a problem? Please describe.**
The scrollbar look is not better. 

**Describe the solution you'd like**
Change the Scrollbar styles such as colour and size

**Additional context**
Use the following link to learn about it
[https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp](url)

**Are you working on it?**
No

**Comment by roshan798** [comment]
I want to work in this, please assign this to me.

**Comment by Tharindu37** [comment]
@roshan798 Sure, go ahead
