### ISSUE TITLE
Scroll down to the "Technology" section

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#94]
**Is your feature request related to a problem? Please describe.**
Doesn't scroll down to the "Technology" section when clicking the "Technology" link at top of the nav bar

**Describe the solution you'd like**
Use the HTML Hyperlinks

**Are you working on it?**
No

**Comment by Mattias988** [comment]
I would like to assigned

**Comment by Tharindu37** [comment]
@Mattias988 Sure, go ahead

**Comment by Mattias988** [comment]
I'm sorry but i'm  a bit new at github. How to do a git push if i don't have permission? I think that i fixed an issue

**Comment by Tharindu37** [comment]
@Mattias988 did you look at the Readme file?

**Comment by Tharindu37** [comment]
@Mattias988 What is the status of this?

**Comment by Mattias988** [comment]
@Tharindu37 I did as it was written in README.

**Comment by Tharindu37** [comment]
@Mattias988 What is the issue now?

**Comment by Mattias988** [comment]
@Tharindu37 i don't know, i did everything as it was in readme and after that i fixed the issue, did a commit and push. I don't really know what to do now

**Comment by Tharindu37** [comment]
@Mattias988 Did you add the upstream?

**Comment by Mattias988** [comment]
@Tharindu37 yup

**Comment by Tharindu37** [comment]
@Mattias988 What is the issue now?

**Comment by rohit-rambade** [comment]
Any one working on this issue ? if not then assign to me

**Comment by Tharindu37** [comment]
@rohit-rambade Ok, I will be assigned if @Mattias988 is not done
